<?php
return [
    [
        "id" => 8,
        "name" => "Mercurio",
        "diameter_km" => 4879,
        "mass_kg" => 3.3011e23,
        "average_distance_from_sun_km" => 57910000,
        "orbital_period_days" => 88,
        "moons" => 0,
        "atmospheric_composition" => "Ossigeno, Sodio, Idrogeno, Elio, Potassio",
        "average_temperature_celsius" => 167,
        "type" => "Terrestre",
        "description" => "Mercurio è il primo pianeta del sistema solare in ordine di distanza dal Sole e il più interno del nostro sistema planetario. È il più piccolo e la sua orbita è anche la più eccentrica, ovvero la meno circolare, degli otto pianeti. Mercurio orbita in senso diretto (in senso antiorario, come tutti gli altri pianeti del sistema solare) a una distanza media di 0,3871 au dal Sole con un periodo siderale di 87,969 giorni terrestri. Mercurio è anche in risonanza orbitale-rotazionale: completa tre rotazioni intorno al proprio asse ogni due orbite attorno al Sole. L'eccentricità orbitale è abbastanza elevata e vale 0,205, ben 15 volte quella della Terra. Dalla superficie di Mercurio, il Sole ha un diametro apparente medio di 1,4°, circa 2,8 volte quello visibile dalla Terra, e arriva a 1,8° durante il passaggio al perielio. Il rapporto fra la radiazione solare al perielio e quella all'afelio è 2,3. Per la Terra questo rapporto vale 1,07[6]. La superficie di Mercurio sperimenta la maggiore escursione termica tra tutti i pianeti, con temperature che nelle regioni equatoriali vanno da 100 K (−173 °C) della notte a 700 K (427 °C) del dì; le regioni polari invece sono costantemente inferiori a 180 K (−93 °C). Ciò è dovuto all'assenza dell'atmosfera che, se presente, svolgerebbe un ruolo nella ridistribuzione del calore. La superficie fortemente craterizzata indica che Mercurio è geologicamente inattivo da miliardi di anni. Conosciuto sin dal tempo dei Sumeri, il suo nome è tratto dalla mitologia romana. Il pianeta è stato associato a Mercurio, messaggero degli dèi, probabilmente a causa della rapidità del suo movimento nel cielo. Il suo simbolo astronomico è una versione stilizzata del caduceo del dio.",
        "link" => "https://it.wikipedia.org/wiki/Mercurio_(astronomia)",
        "video" => "videos/mercury.mp4",

    ],
    [
        "id" => 7,
        "name" => "Venere",
        "diameter_km" => 12104,
        "mass_kg" => 4.8675e24,
        "average_distance_from_sun_km" => 108200000,
        "orbital_period_days" => 225,
        "moons" => 0,
        "atmospheric_composition" => "Diossido di carbonio, Azoto, Anidride solforosa",
        "average_temperature_celsius" => 464,
        "type" => "Terrestre",
        "description" => "Venere è il secondo pianeta del sistema solare in ordine di distanza dal Sole con un'orbita quasi circolare che lo porta a compiere una rivoluzione in 225 giorni terrestri. Prende il nome dalla dea romana dell'amore e della bellezza e il suo simbolo astronomico è la rappresentazione stilizzata della mano di Venere che sorregge uno specchio. Con una magnitudine massima di −4,6, è l'oggetto naturale più luminoso nel cielo notturno dopo la Luna e per questo motivo è conosciuto fin dall'antichità. Venere è visibile soltanto poco dopo il tramonto e poco prima dell'alba e per questa ragione è spesso stato chiamato dagli antichi Greci (e poi dai Romani) stella della sera o stella del mattino. La scoperta che si tratta dello stesso oggetto sarebbe stata introdotta in occidente da Pitagora, ma sarebbe dovuta agli astronomi della Mesopotamia. Infatti nella Tavoletta di Venere di Ammi-saduqa sono riportate osservazioni risalenti al 1550 a.C. o antecedenti, in cui non si fa distinzione fra l'astro del mattino e quello della sera. Classificato come un pianeta terrestre, a volte è definito il 'pianeta gemello' della Terra, cui è molto simile per dimensioni e massa. Tuttavia per altri aspetti è piuttosto differente dal nostro pianeta. L'atmosfera di Venere è costituita principalmente da anidride carbonica ed è molto più densa dell'atmosfera terrestre, con una pressione al livello del suolo pari a 92 atm. La densità e la composizione dell'atmosfera creano un impressionante effetto serra che rende Venere il pianeta più caldo del sistema solare.Venere è avvolto da uno spesso strato di nubi altamente riflettenti, composte principalmente di acido solforico, che impediscono la visione nello spettro visibile della superficie dallo spazio. Il pianeta non è dotato di satelliti o anelli e ha un campo magnetico più debole di quello terrestre.",
        "link" => "https://it.wikipedia.org/wiki/Venere_(astronomia)",
        "video" => "videos/venus.mp4",
    ],
    [
        "id" => 6,
        "name" => "Terra",
        "diameter_km" => 12742,
        "mass_kg" => 5.97237e24,
        "average_distance_from_sun_km" => 149600000,
        "orbital_period_days" => 365.25,
        "moons" => 1,
        "atmospheric_composition" => "Azoto, Ossigeno, Argon, Anidride carbonica",
        "average_temperature_celsius" => 15,
        "type" => "Terrestre",
        "description" => "La Terra è il terzo pianeta in ordine di distanza dal Sole ed è il più grande tra i pianeti terrestri del sistema solare, per massa e per dimensioni. Sulla sua superficie, si trova acqua, presente in tutti e tre gli stati di aggregazione (solido, liquido e gassoso) e un'atmosfera composta in prevalenza da azoto e ossigeno che, insieme al campo magnetico che avvolge il pianeta, ne protegge la biosfera dai raggi cosmici e dalle radiazioni solari. Essendo l'unico corpo planetario del sistema solare adatto a sostenere la vita come concepita e conosciuta dagli esseri umani, è l'unico luogo nel quale vivono tutte le specie viventi conosciute.La sua formazione è datata a circa 4,54 miliardi di anni fa. La Terra possiede un satellite naturale chiamato Luna la cui età, stimata analizzando alcuni campioni delle rocce più antiche, è risultata compresa tra 4,29 e 4,56 miliardi di anni. L'asse di rotazione terrestre è inclinato rispetto alla perpendicolare al piano dell'eclittica: questa inclinazione combinata con la rivoluzione della Terra intorno al Sole causa l'alternarsi delle stagioni. Le condizioni atmosferiche primordiali sono state alterate in maniera preponderante dalla presenza di forme di vita che hanno creato un diverso equilibrio ecologico plasmando la superficie del pianeta. Circa il 71% della superficie è coperta da oceani di acqua salata e il restante 29% è rappresentato dai continenti e dalle isole.La superficie esterna è suddivisa in diversi segmenti rigidi detti placche tettoniche che si spostano lungo la superficie in periodi di diversi milioni di anni. La parte interna, attiva dal punto di vista geologico, è composta da uno spesso strato relativamente solido o plastico, denominato mantello, e da un nucleo diviso a sua volta in nucleo esterno, dove si genera il campo magnetico, e nucleo interno solido, costituito principalmente da ferro e nichel. Tutto ciò che riguarda la composizione della parte interna della Terra resta comunque una teoria indiretta ovvero mancante di verifica e osservazione diretta. Importanti sono le influenze esercitate sulla Terra dallo spazio esterno. Infatti la Luna è all'origine del fenomeno delle maree, stabilizza lo spostamento dell'asse terrestre e ha lentamente modificato la lunghezza del periodo di rotazione del pianeta rallentandolo; un bombardamento di comete durante le fasi primordiali ha giocato un ruolo fondamentale nella formazione degli oceani e in un periodo successivo alcuni impatti di asteroidi hanno provocato significativi cambiamenti delle caratteristiche della superficie e ne hanno alterato la vita presente.",
        "link" => "https://it.wikipedia.org/wiki/Terra",
        "video" => "videos/earth.mp4",
    ],
    [
        "id" => 5,
        "name" => "Marte",
        "diameter_km" => 6779,
        "mass_kg" => 6.4171e23,
        "average_distance_from_sun_km" => 227900000,
        "orbital_period_days" => 687,
        "moons" => 2,
        "atmospheric_composition" => "Diossido di carbonio, Azoto, Argon, Ossigeno",
        "average_temperature_celsius" => -63,
        "type" => "Terrestre",
        "description" => "Marte è il quarto pianeta del sistema solare in ordine di distanza dal Sole; è visibile a occhio nudo ed è l'ultimo dei pianeti di tipo terrestre dopo Mercurio, Venere e la Terra (1,52 UA di distanza dal Sole). Chiamato pianeta rosso per via del suo colore caratteristico causato dalla grande quantità di ossido di ferro che lo ricopre, Marte prende il nome dall'omonima divinità della mitologia romana e il suo simbolo astronomico è la rappresentazione stilizzata dello scudo e della lancia del dio. Pur presentando temperature medie superficiali piuttosto basse (tra −120 e −14 °C) e un'atmosfera molto rarefatta, è il pianeta più simile alla Terra tra quelli del sistema solare. Le sue dimensioni sono intermedie tra quelle del nostro pianeta e quelle della Luna, e l'inclinazione del suo asse di rotazione e la durata del giorno sono molto simili a quelle terrestri. La sua superficie presenta formazioni vulcaniche, valli, calotte polari e deserti sabbiosi, e formazioni geologiche che vi suggeriscono la presenza di un'idrosfera in un lontano passato. La superficie del pianeta appare fortemente craterizzata, a causa della quasi totale assenza di agenti erosivi (principalmente, l'attività geologica, atmosferica e idrosferica) e dalla totale assenza di attività tettonica delle placche capace di formare e poi modellare le strutture tettoniche. La bassissima densità dell'atmosfera non è poi in grado di consumare buona parte delle meteore, che pertanto raggiungono il suolo con maggior frequenza che non sulla Terra. Tra le formazioni geologiche più notevoli di Marte si segnalano: l'Olympus Mons, o monte Olimpo, il vulcano più grande del sistema solare (alto 27 km); le Valles Marineris, un lungo canyon notevolmente più esteso di quelli terrestri; e un enorme cratere sull'emisfero boreale, ampio circa il 40% dell'intera superficie marziana. All'osservazione diretta, Marte presenta variazioni di colore, imputate storicamente alla presenza di vegetazione stagionale, che si modificano al variare dei periodi dell'anno; ma successive osservazioni spettroscopiche dell'atmosfera hanno da tempo fatto abbandonare l'ipotesi che vi potessero essere mari, canali e fiumi oppure un'atmosfera sufficientemente densa. La smentita finale arrivò dalla missione Mariner 4, che nel 1965 mostrò un pianeta desertico e arido, animato da tempeste di sabbia periodiche e particolarmente violente. Le missioni più recenti hanno evidenziato la presenza di acqua ghiacciata. Intorno al pianeta orbitano due satelliti naturali, Fobos e Deimos, di piccole dimensioni e dalla forma irregolare.",
        "link" => "https://it.wikipedia.org/wiki/Marte_(astronomia)",
        "video" => "videos/mars.mp4",
    ],
    [
        "id" => 4,
        "name" => "Giove",
        "diameter_km" => 139820,
        "mass_kg" => 1.8982e27,
        "average_distance_from_sun_km" => 778500000,
        "orbital_period_days" => 4333,
        "moons" => 95,
        "atmospheric_composition" => "Idrogeno, Elio, Metano, Ammoniaca",
        "average_temperature_celsius" => -145,
        "type" => "Gigante gassoso",
        "description" => "Giove (dal latino Iovem, accusativo di Iuppiter) è il quinto pianeta del sistema solare in ordine di distanza dal Sole e il più grande di tutto il sistema planetario: la sua massa corrisponde a due volte e mezzo la somma di quelle di tutti gli altri pianeti messi insieme.È classificato, al pari di Saturno, Urano e Nettuno, come gigante gassoso (gli ultimi due si differenziano per essere classificati in tempi recenti come giganti ghiacciati). Giove ha una composizione simile a quella del Sole: infatti è costituito principalmente da idrogeno ed elio con piccole quantità di altri gas composti, quali ammoniaca, metano e acqua. Si ritiene che il pianeta possegga una struttura pluristratificata, con un nucleo solido, presumibilmente di natura rocciosa e costituito da carbonio e silicati di ferro, sopra il quale gravano un mantello di idrogeno metallico e una vasta copertura atmosferica che esercitano su di esso altissime pressioni. L'atmosfera esterna è caratterizzata da numerose bande e zone di tonalità variabili dal color crema al marrone, costellate da formazioni cicloniche e anticicloniche, tra le quali spicca la Grande Macchia Rossa. La rapida rotazione del pianeta gli conferisce l'aspetto di uno sferoide schiacciato ai poli e genera un intenso campo magnetico che dà origine ad un'estesa magnetosfera; inoltre, a causa del meccanismo di Kelvin-Helmholtz, Giove (come tutti gli altri giganti gassosi) emette una quantità di energia superiore a quella che riceve dal Sole. A causa delle sue dimensioni e della composizione simile a quella solare, Giove è stato considerato per lungo tempo una 'stella fallita': in realtà solamente se avesse avuto l'opportunità di accrescere la propria massa sino a 75-80 volte quella attuale il suo nucleo avrebbe potuto ospitare le condizioni di temperatura e pressione favorevoli all'innesco delle reazioni di fusione dell'idrogeno in elio, cosa che avrebbe reso il sistema solare un sistema stellare binario. L'intenso campo gravitazionale di Giove influenza il sistema solare nella sua struttura perturbando le orbite degli altri pianeti e lo 'ripulisce' in parte dai detriti che possono colpire i pianeti più interni. Intorno a Giove orbitano numerosi satelliti e un sistema di anelli scarsamente visibili; l'azione combinata dei campi gravitazionali di Giove e del Sole, inoltre, stabilizza le orbite di due gruppi di asteroidi troiani. Il pianeta, conosciuto sin dall'antichità, ha rivestito un ruolo preponderante nel credo religioso di numerose culture, tra cui i Babilonesi, i Greci e i Romani, che lo hanno identificato con il sovrano degli dei. Il simbolo astronomico del pianeta è una rappresentazione stilizzata del fulmine, principale attributo di quella divinità.",
        "link" => "https://it.wikipedia.org/wiki/Giove_(astronomia)",
        "video" => "videos/jupiter.mp4",
    ],
    [
        "id" => 3,
        "name" => "Saturno",
        "diameter_km" => 116460,
        "mass_kg" => 5.6834e26,
        "average_distance_from_sun_km" => 1433000000,
        "orbital_period_days" => 10759,
        "moons" => 146,
        "atmospheric_composition" => "Idrogeno, Elio, Metano, Ammoniaca",
        "average_temperature_celsius" => -178,
        "type" => "Gigante gassoso",
        "description" => "Saturno è il sesto pianeta del sistema solare in ordine di distanza dal Sole e il secondo pianeta più massiccio, dopo Giove. Rispetto alla Terra, ha un raggio medio 9,48 volte maggiore e una massa 95 volte superiore. Saturno è classificato come gigante gassoso, insieme a Giove, Urano e Nettuno, ed è composto per il 95% da idrogeno e per il 3% da elio, a cui seguono gli altri elementi; il nucleo, consistente in silicati e ghiacci, è circondato da uno spesso strato di idrogeno metallico e quindi da uno strato esterno gassoso. Il pianeta ha un esteso e vistoso sistema di anelli esterni, che consistono principalmente in particelle di ghiaccio e polveri di silicati. Insieme agli anelli, orbitano 146 lune conosciute, e per questo Saturno detiene il primato per il maggior numero di satelliti, nel sistema solare. Tra queste lune, Titano è la più grande (più grande di Mercurio e Plutone) ed anche l'unica del sistema solare ad avere un'atmosfera di grandissimo interesse. I venti, nell'atmosfera di Saturno, possono raggiungere i 1800 km/h, risultando significativamente più veloci di quelli su Giove e leggermente meno veloci di quelli che spirano nell'atmosfera di Nettuno. Il nome di Saturno deriva dall'omonimo dio della mitologia romana, omologo del titano greco Crono. Il suo simbolo astronomico è una rappresentazione stilizzata della falce del dio dell'agricoltura.",
        "link" => "https://it.wikipedia.org/wiki/Saturno_(astronomia)",
        "video" => "videos/saturn.mp4",
    ],
    [
        "id" => 2,
        "name" => "Urano",
        "diameter_km" => 50724,
        "mass_kg" => 8.6810e25,
        "average_distance_from_sun_km" => 2871000000,
        "orbital_period_days" => 30687,
        "moons" => 27,
        "atmospheric_composition" => "Idrogeno, Elio, Metano",
        "average_temperature_celsius" => -224,
        "type" => "Gigante ghiacciato",
        "description" => "Urano è il settimo pianeta del sistema solare in ordine di distanza dal Sole, il terzo per diametro e il quarto per massa. Porta il nome del dio greco del cielo, padre di Crono (Saturno) e nonno di Zeus (Giove).La composizione chimica di Urano è simile a quella di Nettuno ma differente rispetto a quella dei giganti gassosi più grandi (Giove e Saturno). Per questa ragione gli astronomi talvolta preferiscono riferirsi a Urano e Nettuno trattandoli come una classe separata, i 'giganti ghiacciati'. L'atmosfera del pianeta, sebbene sia simile a quella di Giove e Saturno per la presenza abbondante di idrogeno ed elio, contiene una proporzione elevata di 'ghiacci', come l'acqua, l'ammoniaca e il metano, assieme a tracce di idrocarburi. Quella di Urano è anche l'atmosfera più fredda del sistema solare, con una temperatura minima che può scendere fino a 49 K (−224,2 °C). Possiede una complessa struttura di nubi ben stratificata, in cui si pensa che l'acqua si trovi negli strati inferiori e il metano in quelli più in quota. L'interno del pianeta al contrario sarebbe composto principalmente di ghiacci e rocce. Una delle caratteristiche più insolite del pianeta è l'orientamento del suo asse di rotazione. Tutti gli altri pianeti hanno il proprio asse quasi perpendicolare al piano dell'orbita, mentre quello di Urano è quasi parallelo. Ruota quindi esponendo al Sole uno dei suoi poli per metà del periodo di rivoluzione, con conseguente estremizzazione delle fasi stagionali.",
        "link" => "https://it.wikipedia.org/wiki/Urano_(astronomia)",
        "video" => "videos/uranus.mp4",
    ],
    [
        "id" => 1,
        "name" => "Nettuno",
        "diameter_km" => 49244,
        "mass_kg" => 1.02413e26,
        "average_distance_from_sun_km" => 4495000000,
        "orbital_period_days" => 60190,
        "moons" => 14,
        "atmospheric_composition" => "Idrogeno, Elio, Metano",
        "average_temperature_celsius" => -214,
        "type" => "Gigante ghiacciato",
        "description" => "Nettuno è l'ottavo e più lontano pianeta del Sistema solare partendo dal Sole. Si tratta del quarto pianeta più grande, considerando il suo diametro, e il terzo se si considera la sua massa. Nettuno ha 17 volte la massa della Terra ed è leggermente più massiccio del suo quasi-gemello Urano, la cui massa è uguale a 15 masse terrestri, ma è meno denso rispetto a Nettuno. Il nome del pianeta è dedicato al dio romano del mare (Nettuno). Nettuno ha una composizione simile a quella di Urano ed entrambi hanno composizioni differenti da quelle dei più grandi pianeti gassosi Giove e Saturno. Per questo sono talvolta classificati in una categoria separata, i cosiddetti 'giganti ghiacciati'. L'atmosfera di Nettuno, sebbene simile a quelle sia di Giove che di Saturno essendo composta principalmente da idrogeno ed elio, possiede anche maggiori proporzioni di 'ghiacci', come acqua, ammoniaca e metano, assieme a tracce di idrocarburi e forse azoto. In contrasto, l'interno del pianeta è composto essenzialmente da ghiacci e rocce come il suo simile Urano. Le tracce di metano presenti negli strati più esterni dell'atmosfera contribuiscono a conferire al pianeta Nettuno il suo colore verde acqua, come Urano.",
        "link" => "https://it.wikipedia.org/wiki/Nettuno_(astronomia)",
        "video" => "videos/neptune.mp4",
    ]
];
